In [43]:
import pandas as pd 
import numpy as np
from surprise import Dataset
import warnings
import operator
import math
warnings.filterwarnings('ignore')

In [44]:
#Full Name	Student ID	First	Last	Cohort	Evening	Location	Phone Number	Email	Career Interests for Matching	Attendance	Module Score	Project Score	Bonus	Total Score


In [46]:
df_st_mat = pd.read_csv("stu_matBig.csv")


In [47]:
df_st_mat = df_st_mat.replace(to_replace = np.nan,  value=0)

In [48]:
df_st_mat.head()

Student  ID  Human Resources  Management  Public Relations  \
0      Adam Ababneh   1              0.0         0.0               1.0   
1      Akhil Modali   2              0.0         1.0               0.0   
2  Alejandra Magana   3              1.0         0.0               0.0   
3   Alexandra Reyes   4              0.0         1.0               1.0   
4    Angeles Chavez   5              1.0         0.0               0.0   

   Communications  Software  Health  Education  Finance  Business  
0             0.0       1.0     0.0        0.0      0.0       0.0  
1             1.0       0.0     0.0        1.0      0.0       0.0  
2             0.0       1.0     1.0        0.0      0.0       0.0  
3             0.0       0.0     0.0        0.0      0.0       1.0  
4             0.0       0.0     0.0        0.0      1.0       0.0

In [49]:
df_vol_mat = pd.read_csv("vol_matBig.csv")


In [50]:
df_vol_mat = df_vol_mat.replace(to_replace = np.nan,  value=0)

In [51]:
df_vol_mat.head()

Volunteer     ID  Human Resources  Management  \
0                    Jiaxian Cai  11111              1.0         0.0   
1  Kevin Orlando Rodezno Polanco  11112              0.0         1.0   
2                 Allison Meyers  11113              0.0         1.0   
3               Suzette Sandoval  11114              0.0         0.0   
4                   Dionne Gayle  11115              1.0         0.0   

   Public Relations  Communications  Software  Health  Education  Finance  \
0               1.0             0.0       1.0     0.0        0.0      1.0   
1               1.0             1.0       0.0     0.0        0.0      0.0   
2               1.0             0.0       1.0     0.0        0.0      0.0   
3               1.0             1.0       0.0     1.0        1.0      0.0   
4               1.0             0.0       1.0     1.0        0.0      0.0   

   Business  
0       0.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0

In [52]:
vol_tuple= []
for i in range (len(df_vol_mat)):
    vol_tuple.append(df_vol_mat.loc[i][1:])

In [53]:
np.asarray(vol_tuple)

array([[11111, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0],
       [11112, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [11113, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
       [11114, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0],
       [11115, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0],
       [11116, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
       [11117, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0],
       [11118, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0],
       [11119, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0]], dtype=object)

# Volunteer Jaccard Array

In [54]:
vol_Array=np.asarray(vol_tuple)
print(vol_Array)
print(vol_Array.shape)

[[11111 1.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 0.0]
 [11112 0.0 1.0 1.0 1.0 0.0 0.0 0.0 0.0 0.0]
 [11113 0.0 1.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0]
 [11114 0.0 0.0 1.0 1.0 0.0 1.0 1.0 0.0 0.0]
 [11115 1.0 0.0 1.0 0.0 1.0 1.0 0.0 0.0 0.0]
 [11116 0.0 1.0 1.0 1.0 0.0 1.0 0.0 0.0 0.0]
 [11117 1.0 1.0 0.0 0.0 1.0 0.0 1.0 0.0 1.0]
 [11118 0.0 1.0 0.0 1.0 0.0 1.0 1.0 1.0 0.0]
 [11119 1.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0]]
(9, 10)


# Student Jaccard Array

In [55]:
Stu_tuple= []
for i in range (len(df_st_mat)):
    Stu_tuple.append(df_st_mat.loc[i][1:])

In [56]:
stu_Array= np.asarray(Stu_tuple)
print(stu_Array)
print(stu_Array.shape)

[[1 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0]
 [2 0.0 1.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0]
 [3 1.0 0.0 0.0 0.0 1.0 1.0 0.0 0.0 0.0]
 [4 0.0 1.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0]
 [5 1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0]
 [6 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0]
 [7 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0]
 [8 0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0]
 [9 1.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0]
 [10 0.0 0.0 0.0 0.0 1.0 0.0 1.0 0.0 1.0]
 [11 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [12 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0]
 [13 0.0 1.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0]
 [14 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0]
 [15 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [16 0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0]
 [17 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 1.0]
 [18 1.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0]
 [19 0.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0]]
(19, 10)


# student Data

In [62]:
stu_list = df_st_mat.values.tolist()
print(stu_list)

[['Adam Ababneh', 1, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0], ['Akhil Modali', 2, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0], ['Alejandra Magana', 3, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0], ['Alexandra Reyes', 4, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0], ['Angeles Chavez', 5, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0], ['Anna Terzian', 6, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0], ['Cameryn Newman', 7, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0], ['Daniella Medina', 8, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0], ['David Oguns', 9, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0], ['Devon Devera', 10, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0], ['Dominic Perez', 11, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], ['Elisa Hong', 12, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0], ['Erik Mariscal Ventura', 13, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0], ['Esther M Roldan Cervantes', 14, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0], ['Evan Pace', 15, 1.0, 0.0, 0.0, 0.0

# Volunteer Data

In [63]:
vol_list = df_vol_mat.values.tolist()
print(vol_list)

[['Jiaxian Cai', 11111, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0], ['Kevin Orlando Rodezno Polanco', 11112, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0], ['Allison Meyers', 11113, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0], ['Suzette Sandoval', 11114, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0], ['Dionne Gayle', 11115, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0], ['Daman Ahluwalia', 11116, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0], ['Meredith Curry', 11117, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0], ['Charles Anderson', 11118, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0], ['Lauren Koehler', 11119, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0]]


In [64]:
#backup loop
# vol_s =[]
# vol_sim={}
# stu_s =[]
# stu_sim={}
# for i in vol_list:
#     v1= i
#     vol_s.append(v1[0:2])
# #     viarr = int(v1[1:])
#     print(v1[1:])
#     sumxx,sumyy,sumxy =0,0,0
# #     print(vol_s[0][1])
# #     print(vol_s)
#     for j in stu_list:
#         v2=j
#         print (v2[1:])
#         stu_s.append(v2[0:2])
#         #cosine
# #         x=v1[2:]
# #         y=v2[2:]
# #         sumxx += x*x
# #         sumyy += y*y
# #         sumxy += x+y
# #         print(sumxy/math.sqrt(sumxx*sumyy))
# #         print(viarr)
        
        
#         break
        
#     break

# Finding Similarities and mapping with volunteer to all the students Volunteer to student confidence calculation

In [65]:
vol_stu_list=[]
for i in vol_Array:
    tupList=[]
    vol_stu_List = []
    sim=0
    v1=i
#     print("1 is here")
    sumxx,sumyy,sumxy =0,0,0
    for j in stu_Array:
#         print("2 is here")
        v2=j
        
        k=0
        
        for k in range(len(v1)):
#             print("3 is here")
            x=v1[k]
            y=v2[k]
#             print(v2)
            sumxx += x*x
            sumyy += y*y
            sumxy += x*y
            sim = sumxy/math.sqrt(sumxx*sumyy)
#         print("4 is here")
        tupList.append((v2[0],sim))
#     print(tupList)
    sortby = sorted(tupList, key= lambda tup: tup[1],reverse=True)
#     print(len(sortby))
#     print(v1)
#     print(sortby[:3])
#     print("here" , v1[0])
    temp = sortby
#     print(temp,'temp')
#     print(v1[0])
    vol_stu_list.append((v1[0],temp))
#     print(list(vol_stu_list))
#     break
# print(vol_stu_list)
   
    
# print(len(vol_stu_list))
    
    
        
#         sortby = tupList.sort(key = lambda tup: tup[0])
#         for q in tupList:
#             print(q)
    
#         print(tupList)
        #2nd for end
        

#     break
# print(vol_stu_list)
# p=0
# for l in (vol_stu_list):
# #     print(vol_stu_list)
# #     print(p,"p")
#     print(vol_stu_list[p][0][0], vol_stu_list[p][1])
#     p=p+1

# list(map(lambda x:print(x),vol_stu_map))

print((vol_stu_list))
# print(dir(vol_stu_list))
# list_vol = list(vol_stu_list)


[(11111, [(19, 0.8690120432085381), (18, 0.8686456237482638), (17, 0.8684027197025109), (16, 0.8681032925788867), (15, 0.8673934439579551), (14, 0.8660380091078482), (13, 0.8646827281321762), (12, 0.8634894443134268), (11, 0.861161600578179), (10, 0.8568851222325842), (9, 0.8533389453903181), (8, 0.8523438665480237), (7, 0.8446401884579444), (6, 0.8327327016560991), (5, 0.8135233705293939), (4, 0.7809039362399531), (3, 0.7385932472904329), (2, 0.6708606320078686), (1, 0.577454183922376)]), (11112, [(19, 0.869010399551025), (18, 0.8686433407028205), (17, 0.8684011900574604), (16, 0.8681009974567915), (15, 0.8673895435134834), (14, 0.8660343002411146), (13, 0.8646793100096144), (12, 0.8634844652824079), (11, 0.8611580801044366), (10, 0.8568823201187701), (9, 0.8533372406549892), (8, 0.8523417376348326), (7, 0.8446320458242016), (6, 0.8327255655680145), (5, 0.8135136096616382), (4, 0.7809039362420875), (3, 0.7385821689476596), (2, 0.6708807541059119), (1, 0.5774022195429488)]), (11113, [(

In [68]:
# print((vol_stu_list))
print("Volunteer count",len(vol_stu_list))
print("Student Count",len(vol_stu_list[0][1]))

Volunteer count 9
Student Count 19


# Mapping for reccomendation

In [69]:
selectedVal=[]
mapList=[]
p=0
size = len(vol_stu_list)
print(len(vol_stu_list[0][1]))
p=0
for q in range(len(vol_stu_list[0][1])):
    comst=[]
    for e in vol_stu_list:
        comst.append((e[0],e[1][p][0],e[1][p][1]))
    comstsort = sorted(comst, key= lambda tup: tup[2],reverse=True)
    mapList.append((comstsort[0:2])) # [0:3] will take top three neighbours
    p=p+1

19


In [70]:
print(mapList)

[[(11117, 19, 0.8690145035332886), (11119, 19, 0.869014501541553)], [(11117, 18, 0.8686483566755319), (11119, 18, 0.8686474407577515)], [(11117, 17, 0.868406795634819), (11119, 17, 0.868405261881582)], [(11117, 16, 0.8681061543458166), (11119, 16, 0.8681055779110722)], [(11117, 15, 0.8673960349107559), (11119, 15, 0.8673947321946451)], [(11117, 14, 0.8660409664654464), (11119, 14, 0.8660394801076827)], [(11117, 13, 0.8646852814067897), (11119, 13, 0.8646852784920331)], [(11117, 12, 0.863492420135997), (11119, 12, 0.86349142130837)], [(11117, 11, 0.8611662835436187), (11119, 11, 0.8611651065037108)], [(11117, 10, 0.8568907153211408), (11119, 10, 0.8568893101408953)], [(11119, 9, 0.8533457501698772), (11116, 9, 0.8533423487380187)], [(11117, 8, 0.8523481121301897), (11115, 8, 0.8523459897226763)], [(11115, 7, 0.8446428935612051), (11117, 7, 0.8446428852665362)], [(11115, 6, 0.8327362588748107), (11111, 6, 0.8327327016560991)], [(11117, 5, 0.8135282271616671), (11111, 5, 0.813523370529393